name: bagl
description: Basic Graphics Library for Dart.
version: 0.5.0
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/bagl.dart
documentation:
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  rl_matrix: '>= 0.6.3 <0.7.0'
  collection: '>= 1.9.0 <2.0.0'
  quiver: '>=0.24.0 <0.25.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
