name: bagl
description: Basic Graphics Library for Dart.
version: 0.6.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/bagl.dart
documentation:
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  rl_matrix: '^0.6.4'
  collection: '^1.9.0'
  quiver: '^0.24.0'
dev_dependencies:
  test: '^0.12.17'
  browser: '^0.10.0'
  dart_to_js_script_rewriter: '^0.1.0'
