name: bagl
description: Basic Graphics Library for Dart.
version: 0.0.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/bagl.dart
documentation:
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  rl_matrix: '>= 0.4.4 <0.5.0'
  collection: '>= 1.2.0 <1.3.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
